language: perl
perl:
  - "5.14"
  - "5.12"
  - "5.10"
notifications:
  email:
    recipients: # feel free to ask if you want to get notified as well
      - zzz@cpan.org
    on_success: always
    on_failure: always
before_install: 
  - sudo apt-get install libpcre3-dev

